name: ${project.artifactId}
api-version: 1.13
main: ${project.groupId}.awa
version: ${project.version}
commands:
   awa:
      description: Awa?
      usage: /<command>
   papawa:
      description: Papawa?
      usage: /<command>