name: ${project.artifactId}
api-version: 1.13
main: ${project.groupId}.awa
version: ${project.version}
commands:
	awa:
		description: Awa?
		usage: /<command>
		aliases: [awita]
	papawa:
		description: Papawa?
		usage: /<command>
		aliases: [papawita]
	dime:
		description: Repite lo que digas.
		usage: /<command>
		aliases: [d]
	cmd:
		description: Commands available.
		usage: /<command>
		aliases: [commands]
