name: MSR-JTest
api-version: 1.13
main: dev.nnnk.jtest1.awa
version: 0.0.12
commands:
   awa:
      description: Awa?
      usage: /<command>
   papawa:
      description: Papawa?
      usage: /<command>