name: MSR-JTest
api-version: 1.13
main: dev.nnnk.jtest1.awa
version: 0.0.1-20200418-200953
commands:
   awa:
      description: Awa?
      usage: /<command>
      aliases: [awita]
   papawa:
      description: Papawa?
      usage: /<command>
      aliases: [papawita]
   dime:
      description: Repite lo que digas.
      usage: /<command>
      aliases: [d]